In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
documents = [
    "Text analysis is an interesting field.",
    "Machine Learning is part of data science.",
    "Text analysis involves understanding data."
]

In [3]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

In [4]:
print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectorized Data (Counts):\n", X.toarray())

Vocabulary: ['an' 'analysis' 'data' 'field' 'interesting' 'involves' 'is' 'learning'
 'machine' 'of' 'part' 'science' 'text' 'understanding']
Vectorized Data (Counts):
 [[1 1 0 1 1 0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 1 1 1 1 1 0 0]
 [0 1 1 0 0 1 0 0 0 0 0 0 1 1]]


In [5]:
from sklearn.feature_extraction.text import TfidfTransformer

In [6]:
tfidf_transformer = TfidfTransformer()
tfidf_matrix = tfidf_transformer.fit_transform(X)

In [7]:
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

TF-IDF Matrix:
 [[0.45954803 0.34949812 0.         0.45954803 0.45954803 0.
  0.34949812 0.         0.         0.         0.         0.
  0.34949812 0.        ]
 [0.         0.         0.30650422 0.         0.         0.
  0.30650422 0.40301621 0.40301621 0.40301621 0.40301621 0.40301621
  0.         0.        ]
 [0.         0.3935112  0.3935112  0.         0.         0.51741994
  0.         0.         0.         0.         0.         0.
  0.3935112  0.51741994]]
