In [1]:
import numpy as np

# Creating a 1D array
one_dimensional_array = np.array([1, 2, 3, 4, 5])
print("1D array:", one_dimensional_array)

1D array: [1 2 3 4 5]


In [2]:
# Creating a 2D array
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(two_dimensional_array)

2D array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Array addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result = array_a + array_b
print("Array addition:", result)

Array addition: [5 7 9]


In [4]:
# Array multiplication
result = array_a * array_b
print("Array multiplication:", result)

Array multiplication: [ 4 10 18]


In [5]:
# Accessing elements
print("First element:", one_dimensional_array[0])
print("Last element:", one_dimensional_array[-1])

First element: 1
Last element: 5


In [6]:
# Slicing a 1D array
print("Slice 1D array:", one_dimensional_array[1:4])

# Slicing a 2D array
print("Slice 2D array:\n", two_dimensional_array[0:2, 1:3])

Slice 1D array: [2 3 4]
Slice 2D array:
 [[2 3]
 [5 6]]
