In [1]:
import numpy as np

# Creating a 3x4 NumPy array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("Original Array:\n", array_2d)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
# Extract elements from 2nd and 3rd column
sliced_array = array_2d[:, 1:3]
print("Sliced Array (columns 2 to 3):\n", sliced_array)

Sliced Array (columns 2 to 3):
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [3]:
# Extract every second element from the array
advanced_slicing = array_2d[::2, ::2]
print("Advanced Slicing:\n", advanced_slicing)

Advanced Slicing:
 [[ 1  3]
 [ 9 11]]


In [4]:
# Add 10 to all elements in the array
added_array = array_2d + 10
print("Array after addition:\n", added_array)

# Multiply each element by 2
multiplied_array = array_2d * 2
print("Array after multiplication:\n", multiplied_array)

Array after addition:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Array after multiplication:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [5]:
# Adding a 1D array to each row of a 2D array
added_with_broadcasting = array_2d + np.array([1, 0, 1, 0])
print("Array after broadcasting:\n", added_with_broadcasting)

Array after broadcasting:
 [[ 2  2  4  4]
 [ 6  6  8  8]
 [10 10 12 12]]


In [6]:
# Reshape a 1D array of 12 elements to a 2D array of shape (3, 4)
reshaped_array = np.arange(12).reshape(3, 4)
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# Flatten a 2D array to a 1D array
flattened_array = array_2d.flatten()
print("Flattened Array:\n", flattened_array)

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# Transpose a 3x4 array to a 4x3 array
transposed_array = array_2d.T
print("Transposed Array:\n", transposed_array)

Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
